# Generated by Django 3.2.11 on 2022-02-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
    ]
