# Generated by Django 3.2.11 on 2022-02-09 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_books_active_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='author_name',
            new_name='author',
        ),
    ]
