# Generated by Django 3.2.11 on 2022-02-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_rename_author_name_books_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
