# Generated by Django 3.2.11 on 2022-02-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_item_orders_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='status',
            field=models.CharField(choices=[('incart', 'incart'), ('cancell', 'cancell'), ('orderplaced', 'orderplaced')], default='incart', max_length=120),
        ),
    ]
